### PR TITLE
correct spelling in documentation

### PR DESCRIPTION
**Pull request by jonnydubowsky**

### CODE REVIEW

**Comment by JEJodesty** [comment]
@jonnydubowsky
Never submit PR to master branch again. 
Always PR to "staging".

**Comment by mzargham** [comment]
@jonnydubowsky its just a matter of how we're managing code
@JEJodesty do we have a "how to contribute page"
now that we're getting more input from new people we should make sure the process is more transparent.

**Comment by jonnydubowsky** [comment]
Got it re: PR's only to "staging". I'll spend some time reviewing other PR's to familiarize myself better with the terrain. I'd be happy to help with onboarding materials as part of my work with 1M Devs. Really digging CadCad.

**Comment by JEJodesty** [comment]
@jonnydubowsky
omg i just read my comment and it sounds harsh
& It was my fault, i should have changed base
im sorry
i was in logic mode at the time lol
telegram me when you see this

**Comment by JEJodesty** [comment]
@jonnydubowsky
I'll submit a PR with the existing contribution guidelines (draft) we have now

**Comment by JEJodesty** [comment]
@jonnydubowsky 
https://github.com/BlockScience/cadCAD/pull/100
This is a PR with a contribution guidelines draft.
Its essentially a PR about submitting PRs haha
Atonement Complete!

**Comment by jonnydubowsky** [comment]
No worries! I totally have been in that zone and didn't take any offense. Thanks for the example PR. Looking forward to digging in further.

**Pull request merged**
